import {
  CLIENT_VERSION,
  CLIENT_VERSION_HEADER,
  DEVICE_ID,
  DEVICE_ID_HEADER,
  DEVICE_OS,
  DEVICE_OS_HEADER,
  ACCEPT_LANGUAGE,
  ACCEPT_LANGUAGE_HEADER
} from './constants';

export const defaultHeaders: Readonly<Record<string, string>> = Object.freeze({
  [DEVICE_OS_HEADER]: DEVICE_OS,
  [DEVICE_ID_HEADER]: DEVICE_ID,
  [CLIENT_VERSION_HEADER]: CLIENT_VERSION,
  [ACCEPT_LANGUAGE_HEADER]: ACCEPT_LANGUAGE
});
